name: CI Pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest   # <-- Add this line

      - name: Run tests
        run: |
          if [ -d "tests" ]; then pytest tests/; else echo "No tests folder, skipping"; fi
